
'Free kick accuracy'
'GK diving'
'GK handling'
'GK kicking'
'GK positioning'
'GK reflexes'
'Heading accuracy'
'Interceptions'
'Jumping'
'Long passing'
'Long shots'
'Marking'
'Penalties         '
'Positioning       '
'Reactions         '
'Short passing     '
'Shot power        '
'Sliding tackle    '
'Sprint speed      '
'Stamina           '
'Standing tackle   '
'Strength          '
'Vision            '
'Volleys           '
